from sqlalchemy import Column, Integer, String, Float, Date, DateTime, Text
from sqlalchemy.sql import func
from app.database.database import Base

class Expense(Base):
    """
    SQLAlchemy model representing an Expense record in the database.
    """
    __tablename__ = "expenses"

    # Unique identifier for each expense, acts as the primary key
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    
    # Title or brief description of the expense (e.g., "Lunch with client")
    title = Column(String(255), nullable=False, index=True)
    
    # Monetary value of the expense
    amount = Column(Float, nullable=False)
    
    # Grouping category for the expense (e.g., "Food", "Travel", "Utilities")
    category = Column(String(100), nullable=False, index=True)
    
    # The date when the expense occurred
    date = Column(Date, nullable=False, index=True)
    
    # Optional field for any extra details or notes
    notes = Column(Text, nullable=True)
    
    # Automatically populated timestamp indicating when the record was created
    # func.now() ensures the timestamp is generated by the database server
    created_at = Column(DateTime(timezone=True), server_default=func.now())
